### PR TITLE
Don't sort non-terminal names in the grammar.

### PR DESCRIPTION
**Pull request by ltratt**
This serves no real purpose, and is slightly confusing for users, who may reasonably expect that the order of non-terminals isn't changed by cfgrammar unless explicitly asked to.

### CODE REVIEW

**Comment by ltratt** [comment]
OK, this is more complicated than I thought. I'll take another look tomorrow, but it may be more effort to fix than it's worth.

**Comment by ltratt** [comment]
@ptersilie Please see if that latest commit does the trick for you.

**Comment by ptersilie** [comment]
Yep, looking good. :)

**Comment by ltratt** [comment]
OK, I'm going to add a comment and squash, at which point it may be worth you doing a quick final review.

**Comment by ptersilie** [comment]
Sure.

**Comment by ltratt** [comment]
OK, try that: note there's now a much longer commit message and a comment in the file (because `linked-hash-map` is no longer actively maintained according to https://github.com/contain-rs/linked-hash-map/ so it would be nice to use a different library in the future, though this should be transparent to the user).

**Comment by ptersilie** [comment]
Nice.

**Pull request merged**
